In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("sales_pipeline.csv")

In [10]:
df.head(11)

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517.0
5,ZNBS69V1,Anna Snelling,MG Special,Ron-tech,Won,2016-10-29,2017-03-01,49.0
6,9ME3374G,Vicki Laflamme,MG Special,J-Texon,Won,2016-10-30,2017-03-02,57.0
7,7GN8Q4LL,Markita Hansen,GTX Basic,Cheers,Won,2016-11-01,2017-03-07,601.0
8,OLK9LKZB,Niesha Huffines,GTX Plus Basic,Zumgoity,Won,2016-11-01,2017-03-03,1026.0
9,HAXMC4IX,James Ascencio,MG Advanced,NaN,Engaging,2016-11-03,NaN,NaN
10,NL3JZH1Z,Anna Snelling,MG Special,Bioholding,Won,2016-11-04,2017-03-10,53.0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  8800 non-null   object
 1   sales_agent     8800 non-null   object
 2   product         8800 non-null   object
 3   account         7375 non-null   object
 4   deal_stage      8800 non-null   object
 5   engage_date     8300 non-null   object
 6   close_date      6711 non-null   object
 7   close_value     6711 non-null   float64
dtypes: float64(1), object(7)
memory usage: 550.1+ KB

In [12]:
df.isnull()

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
8795,False,False,False,True,False,True,True,True
8796,False,False,False,True,False,True,True,True
8797,False,False,False,True,False,True,True,True
8798,False,False,False,True,False,True,True,True
8799,False,False,False,True,False,True,True,True

In [13]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8795    False
8796    False
8797    False
8798    False
8799    False
Length: 8800, dtype: bool

In [14]:
df.isnull().sum()

opportunity_id       0
sales_agent          0
product              0
account           1425
deal_stage           0
engage_date        500
close_date        2089
close_value       2089
dtype: int64

In [15]:
df.duplicated().sum()

0

In [16]:
df.head(10)

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517.0
5,ZNBS69V1,Anna Snelling,MG Special,Ron-tech,Won,2016-10-29,2017-03-01,49.0
6,9ME3374G,Vicki Laflamme,MG Special,J-Texon,Won,2016-10-30,2017-03-02,57.0
7,7GN8Q4LL,Markita Hansen,GTX Basic,Cheers,Won,2016-11-01,2017-03-07,601.0
8,OLK9LKZB,Niesha Huffines,GTX Plus Basic,Zumgoity,Won,2016-11-01,2017-03-03,1026.0
9,HAXMC4IX,James Ascencio,MG Advanced,NaN,Engaging,2016-11-03,NaN,NaN

In [17]:
df['close_value'] = df['close_value'].fillna(0)

In [18]:
df['close_value']

0       1054.0
1       4514.0
2         50.0
3        588.0
4        517.0
         ...
8795       0.0
8796       0.0
8797       0.0
8798       0.0
8799       0.0
Name: close_value, Length: 8800, dtype: float64

In [19]:
df.head()

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517.0

In [20]:
df['engage_date'] = pd.to_datetime(df['engage_date'])

In [21]:
df['engage_date']

0      2016-10-20
1      2016-10-25
2      2016-10-25
3      2016-10-25
4      2016-10-25
          ...
8795          NaT
8796          NaT
8797          NaT
8798          NaT
8799          NaT
Name: engage_date, Length: 8800, dtype: datetime64[ns]

In [23]:
df['deal_stage'] = df['deal_stage'].str.lower().str.strip()

In [24]:
df['deal_stage']

0               won
1               won
2               won
3               won
4               won
           ...
8795    prospecting
8796    prospecting
8797    prospecting
8798    prospecting
8799    prospecting
Name: deal_stage, Length: 8800, dtype: object

In [25]:
df = df.drop_duplicates()

In [27]:
df

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,won,2016-10-20,2017-03-01,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,won,2016-10-25,2017-03-11,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,won,2016-10-25,2017-03-07,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,won,2016-10-25,2017-03-09,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,won,2016-10-25,2017-03-02,517.0
...,...,...,...,...,...,...,...,...
8795,9MIWFW5J,Versie Hillebrand,MG Advanced,NaN,prospecting,NaT,NaN,0.0
8796,6SLKZ8FI,Versie Hillebrand,MG Advanced,NaN,prospecting,NaT,NaN,0.0
8797,LIB4KUZJ,Versie Hillebrand,MG Advanced,NaN,prospecting,NaT,NaN,0.0
8798,18IUIUK0,Versie Hillebrand,MG Advanced,NaN,prospecting,NaT,NaN,0.0
8799,8I5ONXJX,Versie Hillebrand,MG Advanced,NaN,prospecting,NaT,NaN,0.0

In [28]:
df.to_csv("Final_Sales_Pipeline.csv",index=False)